import os
import json
import torch
import torchaudio
import numpy as np
from pathlib import Path
import sys

# Assuming dia2 is cloned in the same parent directory or installed
sys.path.append('/files/dia2') 
try:
    from dia2 import Dia2, GenerationConfig, SamplingConfig
except ImportError:
    print("Warning: dia2 module not found. This script is meant to be run on the RunPod instance where Dia2 is installed.")

def process_transcript(transcript, dia_model, config, output_audio_path, output_text_path):
    # 1. Prepare Dia2 Script and Word-Speaker Mapping
    dia_script = ""
    word_speaker_map = []
    
    for turn in transcript:
        speaker = turn["speaker"] # "A" or "B"
        text = turn["text"]
        
        # Dia2 uses [S1] and [S2]
        speaker_tag = "[S1]" if speaker == "A" else "[S2]"
        dia_script += f"{speaker_tag} {text} "
        
        # Normalize text the same way Dia2 does to keep track of words
        normalized = text.replace("\u2019", "'").replace(":", " ")
        for word in normalized.split():
            word_speaker_map.append((word, speaker))
            
    dia_script = dia_script.strip()
    print(f"Generating audio for: {dia_script[:50]}...")
    
    # 2. Generate Audio with Dia2
    # We use a temporary mono wav file
    temp_wav = "temp_mono.wav"
    result = dia_model.generate(
        dia_script, 
        config=config, 
        output_wav=temp_wav, 
        verbose=False
    )
    
    # 3. Align Timestamps and Create Moshi JSON
    moshi_timestamps = []
    
    # result.timestamps is a list of (word, start_time)
    # We need to estimate end_time. We'll use the start of the next word, 
    # or add 0.3s for the last word.
    
    if len(result.timestamps) != len(word_speaker_map):
        print(f"Warning: Word count mismatch! Dia2 generated {len(result.timestamps)} words, but script has {len(word_speaker_map)}.")
        # Fallback: just use the generated words and guess the speaker based on turns
        # For a robust pipeline, you might want to use a more advanced alignment here if this happens often.
    
    for i, (gen_word, start_time) in enumerate(result.timestamps):
        # Try to get the speaker from our map, default to A if mismatch
        speaker = word_speaker_map[i][1] if i < len(word_speaker_map) else "A"
        
        # Estimate end time
        if i + 1 < len(result.timestamps):
            end_time = result.timestamps[i+1][1]
            # Cap the duration to 1 second to avoid huge gaps during pauses
            end_time = min(end_time, start_time + 1.0)
        else:
            end_time = start_time + 0.5
            
        # kyutai-moshi-finetune format
        speaker_label = "SPEAKER_MAIN" if speaker == "A" else "SPEAKER_USER"
        moshi_timestamps.append([
            gen_word,
            [round(start_time, 3), round(end_time, 3)],
            speaker_label
        ])
        
    # Save Moshi JSON
    with open(output_text_path, "w") as f:
        json.dump({"alignments": moshi_timestamps}, f, indent=2)
        
    # 4. Create Stereo WAV (Left=A, Right=B)
    # Load the mono waveform generated by Dia2
    waveform, sample_rate = torchaudio.load(temp_wav)
    
    # Create two empty channels
    left_channel = torch.zeros_like(waveform)
    right_channel = torch.zeros_like(waveform)
    
    # We will "unmute" the respective channel during the speaker's turn
    # To do this cleanly, we find the start and end times of each speaker's continuous turn
    current_speaker = None
    turn_start_time = 0.0
    
    for i, item in enumerate(moshi_timestamps):
        speaker = "A" if item[2] == "SPEAKER_MAIN" else "B"
        start_time = item[1][0]
        end_time = item[1][1]
        
        if speaker != current_speaker:
            # Speaker changed. 
            current_speaker = speaker
            turn_start_time = start_time
            
        # Calculate sample indices
        start_sample = int(start_time * sample_rate)
        # Add a little buffer to the end time so we don't cut off the audio abruptly
        end_sample = int((end_time + 0.2) * sample_rate) 
        end_sample = min(end_sample, waveform.shape[1])
        
        if speaker == "A":
            left_channel[0, start_sample:end_sample] = waveform[0, start_sample:end_sample]
        else:
            right_channel[0, start_sample:end_sample] = waveform[0, start_sample:end_sample]
            
    # Combine into stereo
    stereo_waveform = torch.cat([left_channel, right_channel], dim=0)
    
    # Save Stereo WAV
    torchaudio.save(output_audio_path, stereo_waveform, sample_rate)
    
    # Cleanup temp file
    if os.path.exists(temp_wav):
        os.remove(temp_wav)
        
    return waveform.shape[1] / sample_rate

def main():
    input_file = "data/outbound/raw_transcripts.json"
    audio_dir = "data/outbound/audio"
    dataset_jsonl = "data/outbound/dataset.jsonl"
    
    os.makedirs(audio_dir, exist_ok=True)
    
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found. Run generate_transcripts.py first.")
        return
        
    with open(input_file, "r") as f:
        transcripts = json.load(f)
        
    print(f"Loaded {len(transcripts)} transcripts.")
    
    try:
        print("Loading Dia2 Model...")
        dia_model = Dia2.from_repo("nari-labs/Dia2-2B", device="cuda", dtype="bfloat16")
        config = GenerationConfig(
            cfg_scale=2.0,
            audio=SamplingConfig(temperature=0.8, top_k=50),
            use_cuda_graph=True,
        )
    except NameError:
        print("Skipping model load (Dia2 not imported). Exiting.")
        return
        
    with open(dataset_jsonl, "w") as f_jsonl:
        for i, transcript in enumerate(transcripts):
            # Format: 001.wav, 001.json
            file_id = f"{i+1:03d}"
            audio_path = os.path.join(audio_dir, f"{file_id}.wav")
            text_path = os.path.join(audio_dir, f"{file_id}.json")
            
            print(f"Processing {file_id}/{len(transcripts)}...")
            duration = process_transcript(transcript, dia_model, config, audio_path, text_path)
            
            # Write to jsonl
            abs_audio_path = os.path.abspath(audio_path)
            f_jsonl.write(json.dumps({"path": abs_audio_path, "duration": duration}) + "\n")
        
    print("\nAll audio and timestamps generated successfully!")
    print(f"Dataset ready at {dataset_jsonl}")

if __name__ == "__main__":
    main()
