import os
import json
import torch
import torchaudio
import numpy as np
from pathlib import Path
import soundfile as sf
import sys
import subprocess

try:
    from dia2 import Dia2, GenerationConfig, SamplingConfig
except Exception as e:
    print(f"Warning: dia2 module not found or broken. Exception: {e}")
    print("Attempting to automatically clone and install dia2 in editable mode...")
    
    parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
    dia2_dir = os.path.join(parent_dir, "dia2")
    
    if not os.path.exists(dia2_dir):
        print(f"Cloning dia2 into {dia2_dir}...")
        subprocess.run(["git", "clone", "https://github.com/nari-labs/dia2.git", dia2_dir], check=True)
    else:
        print(f"Found existing dia2 directory at {dia2_dir}.")
        
    print("Installing dia2 in editable mode...")
    # Use the same python executable to run uv pip install
    subprocess.run(["uv", "pip", "install", "-e", dia2_dir], check=True)
    
    print("\n\n✅ dia2 has been successfully installed in editable mode!")
    print("Please click 'Generate Audio & Timestamps' again to restart the process.")
    sys.exit(0)
    print("Warning: dia2 module not found. Please ensure it is installed via pyproject.toml.")

def process_transcript(transcript, dia_model, config, output_audio_path, output_text_path, system_prompt):
    # 1. Prepare Dia2 Script and Word-Speaker Mapping
    dia_script = ""
    word_speaker_map = []
    
    for turn in transcript:
        speaker = turn["speaker"] # "A" or "B"
        text = turn["text"]
        
        # Dia2 uses [S1] and [S2]
        speaker_tag = "[S1]" if speaker == "A" else "[S2]"
        dia_script += f"{speaker_tag} {text} "
        
        # Normalize text the same way Dia2 does to keep track of words
        normalized = text.replace("\u2019", "'").replace(":", " ")
        for word in normalized.split():
            word_speaker_map.append((word, speaker))
            
    dia_script = dia_script.strip()
    print(f"Generating audio for: {dia_script[:50]}...")
    
    # 2. Generate Audio with Dia2
    # We use a temporary mono wav file
    temp_wav = "temp_mono.wav"
    
    # Look for prefix files in the dia2 directory to stabilize voices
    parent_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
    prefix1 = os.path.join(parent_dir, "dia2", "example_prefix1.wav")
    prefix2 = os.path.join(parent_dir, "dia2", "example_prefix2.wav")
    
    kwargs = {}
    if os.path.exists(prefix1) and os.path.exists(prefix2):
        kwargs["prefix_speaker_1"] = prefix1
        kwargs["prefix_speaker_2"] = prefix2
        kwargs["include_prefix"] = False
        
    result = dia_model.generate(
        dia_script, 
        config=config, 
        output_wav=temp_wav, 
        verbose=False,
        **kwargs
    )
    
    # 3. Align Timestamps and Create Moshi JSON
    moshi_timestamps = []
    
    # result.timestamps is a list of (word, start_time)
    # We need to estimate end_time. We'll use the start of the next word, 
    # or add 0.3s for the last word.
    
    if len(result.timestamps) != len(word_speaker_map):
        print(f"Warning: Word count mismatch! Dia2 generated {len(result.timestamps)} words, but script has {len(word_speaker_map)}.")
        # Fallback: just use the generated words and guess the speaker based on turns
        # For a robust pipeline, you might want to use a more advanced alignment here if this happens often.
    
    for i, (gen_word, start_time) in enumerate(result.timestamps):
        # Try to get the speaker from our map, default to A if mismatch
        speaker = word_speaker_map[i][1] if i < len(word_speaker_map) else "A"
        
        # Estimate end time
        if i + 1 < len(result.timestamps):
            end_time = result.timestamps[i+1][1]
            # Cap the duration to 1 second to avoid huge gaps during pauses
            end_time = min(end_time, start_time + 1.0)
        else:
            end_time = start_time + 0.5
            
        # kyutai-moshi-finetune format
        speaker_label = "SPEAKER_MAIN" if speaker == "A" else "SPEAKER_USER"
        moshi_timestamps.append([
            gen_word,
            [round(start_time, 3), round(end_time, 3)],
            speaker_label
        ])
        
    # Save Moshi JSON
    output_data = {"alignments": moshi_timestamps}
    if system_prompt:
        output_data["text_conditions"] = {"description": system_prompt}
        
    with open(output_text_path, "w") as f:
        json.dump(output_data, f, indent=2)
        
    # 4. Create Stereo WAV (Left=A, Right=B)
    # Load the mono waveform generated by Dia2
    audio_data, sample_rate = sf.read(temp_wav)
    if audio_data.ndim == 1:
        audio_data = np.expand_dims(audio_data, axis=1)
    waveform = torch.from_numpy(audio_data).T.float()
    
    # Create two empty channels
    left_channel = torch.zeros_like(waveform)
    right_channel = torch.zeros_like(waveform)
    
    # We will "unmute" the respective channel during the speaker's turn
    # To do this cleanly, we find the start and end times of each speaker's continuous turn
    current_speaker = None
    turn_start_time = 0.0
    
    for i, item in enumerate(moshi_timestamps):
        speaker = "A" if item[2] == "SPEAKER_MAIN" else "B"
        start_time = item[1][0]
        end_time = item[1][1]
        
        if speaker != current_speaker:
            # Speaker changed. 
            current_speaker = speaker
            turn_start_time = start_time
            
        # Calculate sample indices
        start_sample = int(start_time * sample_rate)
        # Add a little buffer to the end time so we don't cut off the audio abruptly
        end_sample = int((end_time + 0.2) * sample_rate) 
        end_sample = min(end_sample, waveform.shape[1])
        
        if speaker == "A":
            left_channel[0, start_sample:end_sample] = waveform[0, start_sample:end_sample]
        else:
            right_channel[0, start_sample:end_sample] = waveform[0, start_sample:end_sample]
            
    # Combine into stereo
    stereo_waveform = torch.cat([left_channel, right_channel], dim=0)
    
    # Save Stereo WAV
    sf.write(output_audio_path, stereo_waveform.T.numpy(), sample_rate)
    
    # Cleanup temp file
    if os.path.exists(temp_wav):
        os.remove(temp_wav)
        
    return waveform.shape[1] / sample_rate

def main():
    input_file = "data/custom_dataset/raw_transcripts.json"
    audio_dir = "data/custom_dataset/audio"
    dataset_jsonl = "data/custom_dataset/dataset.jsonl"
    
    os.makedirs(audio_dir, exist_ok=True)
    
    if not os.path.exists(input_file):
        print(f"Error: {input_file} not found. Run generate_transcripts.py first.")
        return
        
    system_prompt = ""
    if os.path.exists("ui_config.json"):
        try:
            with open("ui_config.json", "r") as f:
                system_prompt = json.load(f).get("system_prompt", "")
        except:
            pass

    with open(input_file, "r") as f:
        transcripts = json.load(f)
        
    print(f"Loaded {len(transcripts)} transcripts.")
    
    # Extract valid UUIDs to clean up orphaned audio files later
    valid_ids = set()
    for t in transcripts:
        if isinstance(t, dict) and "id" in t:
            valid_ids.add(t["id"])
        else:
            # Fallback for old format
            pass
    
    try:
        print("Loading Dia2 Model...")
        dia_model = Dia2.from_repo("nari-labs/Dia2-2B", device="cuda", dtype="bfloat16")
        config = GenerationConfig(
            cfg_scale=3.0,
            audio=SamplingConfig(temperature=0.7, top_k=50),
            use_cuda_graph=True,
        )
    except NameError:
        print("Skipping model load (Dia2 not imported). Exiting.")
        return
        
    with open(dataset_jsonl, "w") as f_jsonl:
        for i, transcript_obj in enumerate(transcripts):
            if isinstance(transcript_obj, list):
                transcript_id = f"legacy_{i+1:03d}"
                transcript = transcript_obj
                valid_ids.add(transcript_id)
            else:
                transcript_id = transcript_obj["id"]
                transcript = transcript_obj["dialogue"]
                
            audio_path = os.path.join(audio_dir, f"{transcript_id}.wav")
            text_path = os.path.join(audio_dir, f"{transcript_id}.json")
            
            if os.path.exists(audio_path) and os.path.exists(text_path):
                print(f"Skipping {transcript_id} (Audio already exists)...")
                # Get duration from existing file
                info = sf.info(audio_path)
                duration = info.frames / info.samplerate
            else:
                print(f"Processing {transcript_id}...")
                duration = process_transcript(transcript, dia_model, config, audio_path, text_path, system_prompt)
            
            # Write to jsonl
            abs_audio_path = os.path.abspath(audio_path)
            f_jsonl.write(json.dumps({"path": abs_audio_path, "duration": duration}) + "\n")
        
    # Cleanup orphaned files (e.g., if a user deleted a row in the UI)
    print("\nCleaning up orphaned audio files...")
    for filename in os.listdir(audio_dir):
        if filename.endswith(".wav") or filename.endswith(".json"):
            file_id = os.path.splitext(filename)[0]
            if file_id not in valid_ids:
                file_path = os.path.join(audio_dir, filename)
                os.remove(file_path)
                print(f"Deleted orphaned file: {filename}")

    print("\nAll audio and timestamps generated successfully!")
    print(f"Dataset ready at {dataset_jsonl}")

if __name__ == "__main__":
    main()
